# This is the default configuration file for Cinema.
# Here is a short tutorial; real settings are at the bottom.

# 1. [media] tables are used to fill your media library.
#
# [media]
# directories = C:\foo, D:/bar
# urls = https://twitch.tv/forsen
# patterns = E:\baz\*.png
# tags = funny, happy
#
# If you type `tag funny`, all media is taken from here.
# Directories are recursive, urls are case-sensitive.
# Patterns support Microsoft wildcard characters.

# 2. [layout] tables specify the number of mpv windows playing media,
# their position and size, and optionally Chatterino.
#
# [layout]
# name = foo
# screen = 10%x10%+0+0
# screen = 480x390+0+650
# chat = 640x945+50+50
#
# Typing `layout foo` will change the layout to this.
# Screen format: https://mpv.io/manual/stable/#options-geometry
# Chat format: [width]x[height]±[x]±[y]
# You can type `store` to write the current layout to file (update).

# 3. [macro] tables are used to do many things at once.
#
# [macro]
# name = foo
# startup = yes
# command = layout foo, tag funny
# command = 1 search forsen, 2 mute
#
# Typing `macro foo` will execute each command, in order.
# Setting startup to `yes` will make this macro run on launch.
# On struggling hardware, you can use `idle` in between commands
# that play media to limit the amount of resources used by mpv.

# Real settings below, you can change everything and add anything.

[media]
urls = https://www.youtube.com/watch?v=AjCGpBUCOOM
tags = you can change this [media] table (and others)

[macro]
name = you can change this [macro] table (and others)
startup = yes
command = idle, layout 1, idle, search watch?, idle, search, idle

[media]
urls = https://twitch.tv/forsen, https://twitch.tv/drututt
urls = https://twitch.tv/pobelter, https://twitch.tv/jackspektra
urls = https://twitch.tv/veigarv2
tags = ff15, superteam, 4 swines

[macro]
name = ff15
startup = no
command = idle
command = layout 5
command = tag ff15
command = idle
command = 1 tw forsen, 2 tw drututt
command = 3 tw pobelter, 4 tw jackspektra
command = 5 tw veigarv2
command = 2 3 4 5 mute

[layout]
name = 1
chat = 509x1045+1418+0
screen = 1425x1040+0+0

[layout]
name = 2
chat = 509x1045+1418+0
screen = 1425x520+0+0
screen = 1425x520+0+520

[layout]
name = 3
chat = 509x396+1418+650
screen = 1920x650+0+0
screen = 712x390+0+650
screen = 713x390+712+650

[layout]
name = 4
chat = 504x396+1423+650
screen = 960x650+0+0
screen = 960x650+960+0
screen = 715x390+0+650
screen = 715x390+715+650

[layout]
name = 5
chat = 493x400+1433+650
screen = 960x650+0+0
screen = 960x650+960+0
screen = 480x390+0+650
screen = 480x390+480+650
screen = 480x390+960+650

[layout]
name = 6
chat = 414x397+1513+650
screen = 960x650+0+0
screen = 960x650+960+0
screen = 380x390+0+650
screen = 380x390+380+650
screen = 380x390+760+650
screen = 380x390+1140+650
